import 'package:flutter/material.dart';
import 'package:movie_app/models/movie_data_class.dart';

class MovieStream extends ChangeNotifier {
final List<Movie> _movies = [

  Movie(
  movieName: "Power",
  posterUrl: "lib/Assets/movie_posters/power.jpeg",
  director: "Courtney A. Kemp",
  description: "James St. Patrick, a wealthy New York nightclub owner, is living a double life as a drug kingpin. He struggles to escape his past while trying to pursue a legitimate business.",
  cast: ["Omari Hardwick", "Lela Loren", "Joseph Sikora", "Naturi Naughton"],
  category: MovieCategory.Drama,
  rating: 8.1,
  releaseDate: DateTime(2014, 6, 7),
  duration: 600, 
  trailerUrl: "lib/Assets/trailers/power.mp4",
  language: "English",
  country: "USA",
),


  Movie(
  movieName: "La Casa de Papel",
  posterUrl: "lib/Assets/movie_posters/lacasa de papel.jpeg",
  director: "Álex Pina",
  description: "A criminal mastermind plans the biggest heist in recorded history, to print billions of euros in the Royal Mint of Spain, using a group of skilled criminals.",
  cast: ["Úrsula Corberó", "Alvaro Morte", "Itziar Ituño", "Pedro Alonso"],
  category: MovieCategory.Drama,
  rating: 8.3,
  releaseDate: DateTime(2017, 5, 2),
  duration: 270, 
  trailerUrl: "lib/Assets/trailers/lacasa.mp4",
  language: "Spanish",
  country: "Spain",
),

Movie(
  movieName: "Prison Break",
  posterUrl: "lib/Assets/movie_posters/Prison Break.jpeg",
  director: "Paul Scheuring",
  description: "An innocent man is sentenced to death for a crime he didn't commit. His only hope is to have his brother break him out of prison.",
  cast: ["Wentworth Miller", "Dominic Purcell", "Sarah Wayne Callies", "Robert Knepper"],
  category: MovieCategory.Action,
  rating: 8.3,
  releaseDate: DateTime(2005, 8, 29),
  duration: 2240, 
  trailerUrl: "lib/Assets/trailers/prison break.mp4",
  language: "English",
  country: "USA",
),

  Movie(
    movieName: "Inception",
    posterUrl: "lib/Assets/movie_posters/Inception.jpeg",
    director: "Christopher Nolan",
    description: "A thief with the ability to enter people's dreams is given a final chance at redemption.",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    category: MovieCategory.SciFi,
    rating: 8.8,
    releaseDate: DateTime(2010, 7, 16),
    duration: 148,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "The Dark Knight",
    posterUrl: "lib/Assets/movie_posters/The Dark Knight.jpeg",
    director: "Christopher Nolan",
    description: "Batman faces off against the Joker, a criminal mastermind who wants to plunge Gotham into anarchy.",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    category: MovieCategory.Action,
    rating: 9.0,
    releaseDate: DateTime(2008, 7, 18),
    duration: 152,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "The Shawshank Redemption",
    posterUrl: "lib/Assets/movie_posters/The Shawshank Redemption.jpeg",
    director: "Frank Darabont",
    description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    category: MovieCategory.Drama,
    rating: 9.3,
    releaseDate: DateTime(1994, 9, 23),
    duration: 142,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "Avengers: Endgame",
    posterUrl: "lib/Assets/movie_posters/Avengers: Endgame.jpeg",
    director: "Anthony Russo, Joe Russo",
    description: "After the devastating events of Infinity War, the Avengers assemble once more to undo the chaos caused by Thanos.",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
    category: MovieCategory.Action,
    rating: 8.4,
    releaseDate: DateTime(2019, 4, 26),
    duration: 181,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "Parasite",
    posterUrl: "lib/Assets/movie_posters/Parasite.jpeg",
    director: "Bong Joon-ho",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    category: MovieCategory.Thriller,
    rating: 8.6,
    releaseDate: DateTime(2019, 5, 30),
    duration: 132,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "Korean",
    country: "South Korea",
  ),
  Movie(
    movieName: "Interstellar",
    posterUrl: "lib/Assets/movie_posters/Interstellar.jpeg",
    director: "Christopher Nolan",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    category: MovieCategory.SciFi,
    rating: 8.6,
    releaseDate: DateTime(2014, 11, 7),
    duration: 169,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "The Godfather",
    posterUrl: "lib/Assets/movie_posters/The Godfather.jpeg",
    director: "Francis Ford Coppola",
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    cast: ["Marlon Brando", "Al Pacino", "James Caan"],
    category: MovieCategory.Drama,
    rating: 9.2,
    releaseDate: DateTime(1972, 3, 24),
    duration: 175,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "Joker",
    posterUrl: "lib/Assets/movie_posters/Joker.jpeg",
    director: "Todd Phillips",
    description: "In Gotham City, a mentally troubled comedian embarks on a downward spiral that leads to the creation of an iconic villain.",
    cast: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz"],
    category: MovieCategory.Thriller,
    rating: 8.4,
    releaseDate: DateTime(2019, 10, 4),
    duration: 122,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "The Matrix",
    posterUrl: "lib/Assets/movie_posters/The Matrix.jpeg",
    director: "Lana Wachowski, Lilly Wachowski",
    description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    category: MovieCategory.SciFi,
    rating: 8.7,
    releaseDate: DateTime(1999, 3, 31),
    duration: 136,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "Pulp Fiction",
    posterUrl: "lib/Assets/movie_posters/Pulp Fiction.jpeg",
    director: "Quentin Tarantino",
    description: "The lives of two mob hitmen, a boxer, a gangster, and his wife intertwine in four tales of violence and redemption.",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    category: MovieCategory.Thriller,
    rating: 8.9,
    releaseDate: DateTime(1994, 10, 14),
    duration: 154,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "Forrest Gump",
    posterUrl: "lib/Assets/movie_posters/Forrest Gump.jpeg",
    director: "Robert Zemeckis",
    description: "The life story of Forrest Gump, a man with low intelligence but a pure heart, as he witnesses significant historical events.",
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    category: MovieCategory.Drama,
    rating: 8.8,
    releaseDate: DateTime(1994, 7, 6),
    duration: 142,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "Fight Club",
    posterUrl: "lib/Assets/movie_posters/Fight Club.jpeg",
    director: "David Fincher",
    description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much more.",
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    category: MovieCategory.Drama,
    rating: 8.8,
    releaseDate: DateTime(1999, 10, 15),
    duration: 139,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "Schindler's List",
    posterUrl: "lib/Assets/movie_posters/Schindler's List.jpeg",
    director: "Steven Spielberg",
    description: "The true story of a businessman who saved over a thousand Jewish refugees during the Holocaust.",
    cast: ["Liam Neeson", "Ralph Fiennes", "Ben Kingsley"],
    category: MovieCategory.Drama,
    rating: 9.0,
    releaseDate: DateTime(1993, 12, 15),
    duration: 195,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "The Lord of the Rings: The Fellowship of the Ring",
    posterUrl: "lib/Assets/movie_posters/The Lord of the Rings: The Fellowship of the Ring.jpeg",
    director: "Peter Jackson",
    description: "A meek hobbit of the Shire and eight companions set out on a journey to destroy the One Ring and save Middle-earth.",
    cast: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
    category: MovieCategory.Fantasy,
    rating: 8.8,
    releaseDate: DateTime(2001, 12, 19),
    duration: 178,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "New Zealand",
  ),
  Movie(
    movieName: "Gladiator",
    posterUrl: "lib/Assets/movie_posters/Gladiator.jpeg",
    director: "Ridley Scott",
    description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
    category: MovieCategory.Action,
    rating: 8.5,
    releaseDate: DateTime(2000, 5, 5),
    duration: 155,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "The Silence of the Lambs",
    posterUrl: "lib/Assets/movie_posters/The Silence of the Lambs.jpeg",
    director: "Jonathan Demme",
    description: "A young FBI cadet must receive the help of an imprisoned and manipulative cannibal killer to catch another serial killer.",
    cast: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
    category: MovieCategory.Thriller,
    rating: 8.6,
    releaseDate: DateTime(1991, 2, 14),
    duration: 118,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "Titanic",
    posterUrl: "lib/Assets/movie_posters/Titanic.jpeg",
    director: "James Cameron",
    description: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane"],
    category: MovieCategory.Romance,
    rating: 7.8,
    releaseDate: DateTime(1997, 12, 19),
    duration: 195,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "Star Wars: Episode IV - A New Hope",
    posterUrl: "lib/Assets/movie_posters/Star Wars: Episode IV - A New Hope.jpeg",
    director: "George Lucas",
    description: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire's world-destroying battle station.",
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
    category: MovieCategory.SciFi,
    rating: 8.6,
    releaseDate: DateTime(1977, 5, 25),
    duration: 121,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "Spider-Man: Into the Spider-Verse",
    posterUrl: "lib/Assets/movie_posters/Spider-Man: Into the Spider-Verse.jpeg",
    director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    description: "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five other-dimensional Spider-Men to stop a threat to all realities.",
    cast: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld"],
    category: MovieCategory.Animation,
    rating: 8.4,
    releaseDate: DateTime(2018, 12, 14),
    duration: 117,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
  Movie(
    movieName: "The Lion King",
    posterUrl: "lib/Assets/movie_posters/The Lion King.jpeg",
    director: "Roger Allers, Rob Minkoff",
    description: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
    cast: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"],
    category: MovieCategory.Animation,
    rating: 8.5,
    releaseDate: DateTime(1994, 6, 24),
    duration: 88,
    trailerUrl: "lib/Assets/trailers/power.mp4",
    language: "English",
    country: "USA",
  ),
];

//Getters
 List<Movie> get movies => _movies;

}